pipelines:
  branches:
    main:
      - step:
          name: Generate SDKs and Pull Request
          image: node:20
          caches:
            - node
          script:
            - |
              if [ -z "$LIBLAB_TOKEN" ] || [ -z "$LIBLAB_BITBUCKET_TOKEN" ]; then
                echo "Error: Variables LIBLAB_TOKEN and LIBLAB_BITBUCKET_TOKEN are required, see https://developers.liblab.com/tutorials/integrate-with-bitbucket-actions/#create-tokens"
                exit 1
              fi
            - npm install -g liblab
            - liblab build --yes --pr -p bitbucket
  pull-requests:
    '**':
      - step:
          name: Generate SDKs and Pull Request
          image: node:20
          caches:
            - node
          script:
            - |
              if [ -z "$LIBLAB_TOKEN" ] || [ -z "$LIBLAB_BITBUCKET_TOKEN" ]; then
                echo "Error: Variables LIBLAB_TOKEN and LIBLAB_BITBUCKET_TOKEN are required, see https://developers.liblab.com/tutorials/integrate-with-bitbucket-actions/#create-tokens"
                exit 1
              fi
            - npm install -g liblab
            - liblab build --yes --pr -p bitbucket

definitions:
  caches:
    node: ~/.npm
